import { useQuery } from "@tanstack/react-query";
import type { NextPage } from "next";
import Head from "next/head";
import { fetchSchools } from "../utils/queries";
import LoginPage from "../components/login-page";
import SchoolSearch from "../components/school-search";

const Home: NextPage = () => {
  const schoolQuery = useQuery({
    queryKey: ["schools"],
    queryFn: fetchSchools,
  });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-green-500">Hello world</h1>
        {/* login page component */}
        <LoginPage></LoginPage>
        <SchoolSearch></SchoolSearch>
        <pre>{JSON.stringify(schoolQuery, null, 2)}</pre>
      </main>
    </div>
  );
};

export default Home;
