import { useEffect, useLayoutEffect, useRef, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { FaArrowDown } from "react-icons/fa";
import { useForm, Controller } from "react-hook-form";
import { useSpring } from "framer-motion";

import Header from "../components/header";
import SchoolSearch from "../components/school-search";
import { useRouter } from "next/router";
import { calculateScore, LocationType } from "../utils/calculate-score";
import { useGradeMutation } from "../utils/hooks/use-grade";
import { useUser } from "@supabase/auth-helpers-react";
import { upsertProfile } from "../utils/hooks/use-profile";

/** TYPES */
type FormValues = {
  /** School choice */
  school: {
    value: number;
    label: string;
  };
  /** Whether the aid is for in-state or out-of-state */
  location: LocationType;
  /** Amount of aid the institution provides the student */
  aidAmount: number;
};

const Homepage: NextPage = () => {
  /** Next.js router */
  const router = useRouter();
  const user = useUser();

  /** Form State */
  const {
    register,
    handleSubmit,
    watch,
    control,
    formState: { isSubmitting, isSubmitSuccessful, errors },
  } = useForm<FormValues>();
  const [loading, setLoading] = useState(false);
  const schoolValue = watch("school")?.value;
  const locationValue = watch("location");
  const gradeMutation = useGradeMutation();

  useEffect(() => {
    if (user) {
      upsertProfile(user);
    }
  }, [user]);

  const onSubmit = async (data: FormValues) => {
    setLoading(true);
    console.log(data);
    const scoreResult = await calculateScore(
      data.school.value,
      data.aidAmount,
      data.location
    );
    const gradeResult = await gradeMutation.mutateAsync({
      schoolId: data.school.value,
      aidAmount: data.aidAmount,
      location: data.location,
      gradeNum: scoreResult,
      userId: user?.id,
      schoolName: data.school.label,
    });
    console.log("Score Result:", scoreResult);
    console.log("Grade Result:", gradeResult);
    if (scoreResult === undefined || !gradeResult) {
      setLoading(false);
    } else {
      router.push(`/grade-result/${gradeResult.grade_id}`);
    }
  };

  /** Slide Refs */
  const locationRef = useRef<HTMLElement>(null);
  const aidRef = useRef<HTMLElement>(null);

  /** Animation utils */
  /** Source for slide scroll animation: https://codesandbox.io/s/kxv7r?file=/src/App.js */
  const spring = useSpring(0);

  useLayoutEffect(() => {
    spring.onChange((latest) => {
      window.scrollTo(0, latest);
    });
  }, [spring]);

  const moveTo = (to: any) => {
    spring.set(window.pageYOffset, false);
    setTimeout(() => {
      spring.set(to);
    }, 50);
  };

  return (
    <div>
      <Head>
        <title>GradeMyAid</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <section className="relative flex min-h-screen items-center justify-center bg-emerald-100">
          {/* <div className="h-80 w-80 rounded-xl bg-orange-100"></div> */}
          <div className="container mx-auto px-4">
            <h2 className="relative z-10 mx-auto mb-8 max-w-xl text-center text-5xl font-black tracking-wide lg:max-w-2xl lg:text-7xl">
              How good is your financial aid? 💸
            </h2>
            <div className="mx-auto max-w-lg">
              <Controller
                control={control}
                rules={{ required: "An institution is required" }}
                name="school"
                render={({ field: { onChange } }) => (
                  <SchoolSearch handleChange={onChange} />
                )}
              />
            </div>
            {errors?.school && (
              <div className="mx-auto mt-8 w-80 rounded-md bg-red-50 py-2 px-4 text-center">
                <p className="text-red-600">{errors.school.message}</p>
              </div>
            )}
            {schoolValue && (
              <div className="absolute bottom-[10%] left-1/2 -translate-x-1/2 transform text-center">
                <button
                  type="button"
                  onClick={() => moveTo(locationRef?.current?.offsetTop)}
                >
                  <FaArrowDown className="mx-auto animate-bounce text-2xl transition" />
                </button>
              </div>
            )}
          </div>
        </section>
        <section
          className="relative flex min-h-screen items-center justify-center bg-emerald-400"
          ref={locationRef}
        >
          <div className="container mx-auto px-4">
            <h2 className="relative z-10 mx-auto mb-6 max-w-xl text-center text-5xl font-black tracking-wide lg:max-w-3xl lg:text-7xl">
              What type of location is the aid?
            </h2>
            <div className="mx-auto text-center">
              <div className="mx-auto flex w-56 flex-col rounded-2xl border-2 border-gray-300 bg-white p-4 text-left focus-within:border-emerald-700">
                <div className="flex items-center justify-between">
                  <label htmlFor="inState" className="mr-1 text-xl">
                    In-state
                  </label>
                  <input
                    type="radio"
                    id="inState"
                    value="inState"
                    className="form-radio text-emerald-700 focus:ring-emerald-700"
                    {...register("location", { required: true })}
                  />
                </div>
                <div className="flex items-center justify-between">
                  <label htmlFor="outState" className="mr-1 text-xl">
                    Out-of-state
                  </label>
                  <input
                    type="radio"
                    id="outState"
                    value="outState"
                    className="form-radio text-emerald-700 focus:ring-emerald-700"
                    {...register("location", {
                      required: "The location field is required",
                    })}
                  />
                </div>
              </div>
            </div>
            {errors?.location && (
              <div className="mx-auto mt-8 w-80 rounded-md bg-red-50 py-2 px-4 text-center">
                <p className="text-red-600">{errors.location.message}</p>
              </div>
            )}
            {locationValue && (
              <div className="absolute bottom-[10%] left-1/2 -translate-x-1/2 transform text-center">
                <button
                  type="button"
                  onClick={() => moveTo(aidRef?.current?.offsetTop)}
                >
                  <FaArrowDown className="mx-auto animate-bounce text-2xl transition" />
                </button>
              </div>
            )}
          </div>
        </section>
        <section
          className="relative flex min-h-screen items-center justify-center bg-emerald-500"
          ref={aidRef}
        >
          <div className="container mx-auto px-4">
            <h2 className="relative z-10 mx-auto mb-8 max-w-xl text-center text-5xl font-black tracking-wide lg:max-w-3xl lg:text-7xl">
              What was your yearly aid amount?
            </h2>
            <div className="mx-auto text-center">
              <input
                type="number"
                className="form-input w-80 rounded-full border-2 border-gray-300 px-4 py-2 ring-gray-300 focus:border-emerald-700 focus:outline-none focus:ring-emerald-700"
                placeholder="Enter your yearly aid amount..."
                min="0"
                {...register("aidAmount", {
                  required: "The aid amount field is required",
                })}
              />
            </div>
            {errors?.aidAmount && (
              <div className="mx-auto mt-8 w-80 rounded-md bg-red-50 py-2 px-4 text-center">
                <p className="text-red-600">{errors.aidAmount.message}</p>
              </div>
            )}
            <div className="absolute bottom-1/4 left-1/2 -translate-x-1/2 transform text-center">
              {Object.values(errors)?.length > 0 ? (
                <button
                  type="button"
                  onClick={handleSubmit(onSubmit)}
                  disabled
                  className="min-w-[180px] rounded-full bg-red-300 px-4 py-2 font-bold shadow shadow-emerald-600 transition"
                >
                  There were errors
                </button>
              ) : (
                <button
                  type="button"
                  onClick={handleSubmit(onSubmit)}
                  className="min-w-[180px] rounded-full bg-violet-300 px-4 py-2 font-bold shadow shadow-emerald-600 transition focus-within:scale-105 hover:scale-105"
                >
                  {isSubmitting || loading ? "Loading..." : "Get your rating"}
                </button>
              )}
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default Homepage;
