import { Auth, ThemeSupa } from "@supabase/auth-ui-react";
import Head from "next/head";
import Header from "../components/header";
import supabase from "../utils/supabase";

const SignUpPage = () => {
  return (
    <div>
      <Head>
        <title>Sign Up - GradeMyAid</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="relative flex min-h-screen items-center justify-center bg-emerald-100">
        <div className="w-full max-w-xl rounded-2xl bg-white p-16 shadow-lg shadow-emerald-200">
          <Auth
            supabaseClient={supabase}
            appearance={{ theme: ThemeSupa }}
            theme="default"
            providers={["google", "facebook"]}
            socialLayout="horizontal"
            view="sign_up"
          />
        </div>
      </main>
    </div>
  );
};

export default SignUpPage;
