import type { NextPage } from "next";
import Head from "next/head";
import LoginPage from "../components/login-page";
import ForgotPassword from "../components/forgot-password";
import ResetPassword from "../components/resetpass-page";
import RegisterPage from "../components/register-page";


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* login page component */}
        <LoginPage></LoginPage>
        {/* forgot password component */}
        <ForgotPassword></ForgotPassword>
        {/* reset password component */}
        <ResetPassword></ResetPassword>
          {/* register page component */}
        <RegisterPage></RegisterPage>
      </main>
    </div>
  );
};

export default Home;
